version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - redis
    #depends_on:
     # - redis
    environment: # Pass environment variables to the service
      REDISCLOUD_URL: "redis:6379"
    networks:
      - backend
  redis:
    image: "redis:alpine"
    networks:
      - backend
    ports:
      - "6379:6379"
networks:
  backend: