version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - redis
    environment: # Pass environment variables to the service
      REDISCLOUD_URL: "redis:6379"
    networks:
      - backend
  redis:
    image: "redis:alpine" #could be redis or redis alpine, is the same
    networks:
      - backend
    ports:
      - "6379:6379"
networks:
  backend: # network to communicate containers with each other